config/routes.rb
Rails.application.routes.draw do
  resources :activities
  get 'users/show'

  devise_for :users, controllers: { sessions: "users/sessions" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :users, only: [:show, :edit, :update] do
    resources :closets
    resources :boards
    member do
      get :following, :followers
    end
  end

  namespace :api, :defaults => { :format => 'json' } do
    resources :users, except: [:new, :edit]
    resources :closets, except: [:new, :edit]
    resources :items, except: [:new, :edit]
  end

  resources :items do
    member do
      put "like", to: "items#upvote"
    end
  end

  get '/prices-over-time', to: 'items#prices_over_time'

  resources :closet_items, only: [:create, :new, :destroy]

  resources :relationships, only: [:create, :destroy]

  devise_scope :user do
    authenticated :user do
        root 'boards#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  get '/hidefy', to: 'searches#hidefy'
  resources :searches

end

app/models/closet.rb
# == Schema Information
#
# Table name: closets
#
#  id         :integer          not null, primary key
#  name       :string
#  board_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Closet < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
  has_many :closet_items
  has_many :items, through: :closet_items

  acts_as_votable

  # it returns hash key => highest_standard_deviation, value = the instance of it
  def get_std_all_items
    analytics_hash = {}
    self.items.each do |item|
      analytics_hash[item.stats.standard_deviation] = item
    end
    analytics_hash
  end

  # it returns hash (only the item that has the highest_standard_deviation)
  # key => highest_standard_deviation, value = the instance of it
  def highest_standard_deviation
    highest_standard_deviation_hash = {}
    analytics_hash = self.get_std_all_items
    highest_standard_deviation = analytics_hash.keys.max
    highest_standard_deviation_instance = analytics_hash[highest_standard_deviation]
    highest_standard_deviation_hash[highest_standard_deviation] = highest_standard_deviation_instance
    highest_standard_deviation_hash
  end

  # it returns hash key => price dif value = the instance of it
  def item_price_change_hash
    new_item_list = {}
    self.items.each do |item|
      new_item_list[item.price_dif] = item
    end
    new_item_list
  end


end

app/controllers/api/closets_controller.rb
class Api::ClosetsController < ApplicationController
  def index
    @closets = Closet.all
    render json: @closets
  end
end

app/controllers/closets_controller.rb
class ClosetsController < ApplicationController

  def index
    @closets = Closet.all
  end

  def new
    @closet = Closet.new
  end

  def show
    @closet = Closet.find(params[:id])
  end

  def create
    @closet = Closet.new(closet_params)
    @closet.save
    track_activity(@closet)
    redirect_to '/'
  end

  def destroy
    @closet = Closet.find(params[:id])
    @closet.destroy
    track_activity(@closet)
    redirect_to '/'
  end

  private
  def closet_params
    params.require(:closet).permit(:name, :board_id, :user_id)
  end


end

app/helpers/closets_helper.rb
module ClosetsHelper
end

app/views/closets/_form.html.erb
<%= form_for :closet, url: {action: 'create'} do |f|%>
  <div class="field form-group">
    <%= f.label :name, class: "control-label", for: "inputDefault" %><br>
    <%= f.text_field :name, class: "form-control", id: "inputDefault", style: "width: 250px;" %>
    <%= f.hidden_field :board_id, :value => current_user.board.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/closets/create.html.erb
<h1>Closet#create</h1>
<p>Find me in app/views/closet/create.html.erb</p>

app/views/closets/index.html.erb
<h1>Closet#index</h1>
<p>Find me in app/views/closet/index.html.erb</p>

app/views/closets/new.html.erb
<div class="col-md-9">
  <h1>New Closet</h1><br>
  <%= render 'form' %>
</div>

app/views/closets/show.html.erb
<center><h3><%= @closet.name %></h3>
<%= link_to "delete", {:controller => :closets, :action => 'destroy', :id => @closet.id }, :method => :delete %> | <%= link_to "add new item", new_search_path %></center>


<% @closet.items.in_groups_of(4) do |group| %>
  <div class="row">
    <% group.compact.each do |item| %>
    <div class="col-xs-6 col-sm-3">
      <div class="card">
        
        <%= image_tag item.image_url, :style => "height: 100%"%>
          <div class = 'card_content'>
            <strong>Price: </strong><%= item.prices.last.price %><br>
            <% closet_item = ClosetItem.where(closet_id: @closet.id, item_id: item.id) %>
            <%= link_to item.name, item_path(item) %><br>
            <%= link_to 'Delete', closet_item_path(closet_item[0].id), method: :delete %>
          </div>
      </div>
  </div>
  <% end %>
</div>
<% end %>