config/routes.rb
Rails.application.routes.draw do
  resources :activities
  get 'users/show'

  devise_for :users, controllers: { sessions: "users/sessions" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :users, only: [:show, :edit, :update] do
    resources :closets
    resources :boards
    member do
      get :following, :followers
    end
  end

  namespace :api, :defaults => { :format => 'json' } do
    resources :users, except: [:new, :edit]
    resources :closets, except: [:new, :edit]
    resources :items, except: [:new, :edit]
  end

  resources :items do
    member do
      put "like", to: "items#upvote"
    end
  end

  get '/prices-over-time', to: 'items#prices_over_time'

  resources :closet_items, only: [:create, :new, :destroy]

  resources :relationships, only: [:create, :destroy]

  devise_scope :user do
    authenticated :user do
        root 'boards#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  get '/hidefy', to: 'searches#hidefy'
  resources :searches

end

app/models/search.rb
# == Schema Information
#
# Table name: searches
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Search < ActiveRecord::Base

  attr_accessor :keyword, :source_type

  def initialize(keyword, source_type)
    @keyword = keyword
    @source_type = source_type
  end

  def results
    if self.source_type == 'Amazon'
      self.amazon_hash
    else self.source_type == 'Hidefy'
      self.hidefy_hash
    end
  end

  def amazon_hash
    #source_id = "B014NHULAE"
    client = Adapters::AmazonSearchClient.new
    results = client.amazon_search(self.keyword)
    items = results['ItemSearchResponse']['Items']['Item']
    self.amazon_parser(items)
  end

  def amazon_parser(items)
    results = []
    items.each do |item|
      source_id = item['ASIN']
      name = item['ItemAttributes']['Title']
      url = item['DetailPageURL']
      if item['MediumImage'].blank?
        item['MediumImage'] = ''
      end
      image_url =  item['MediumImage']['URL']
      price = item['OfferSummary']['LowestNewPrice']['FormattedPrice']
      results << self.item_hash(source_id, name, url, image_url, price)
      end
    return results
  end

  def hidefy_hash
    results = Adapters::HidefyConnection.new.query("items")["items"]
    results_array = []
    results.each do |result|
      source_id = result['id']
      name = result['name']
      url = result['url']
      image_url = result['image_url']
      price = result['price'].to_s
      results_array << self.item_hash(source_id, name, url, image_url, price)
    end
    results_array
  end

  def item_hash(source_id, name, url, image_url, price)
    {
      'source_id' => source_id,
      'name' => name,
      'url' => url,
      'image_url' => image_url,
      'price' => price ,
    }
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    keyword = params[:keyword]
    source_type = params[:item][:source_type]
    if keyword.blank?
      redirect_to new_search_path
    else
      @search = Search.new(keyword, source_type)
      @results = @search.results
    end
  end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searches/_amazon.html.erb
<h3><%= @results.length %> items matching "<%= @search.keyword %>" from <%= @search.source_type %> </h3>

<% @results.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |result| %>
      <center>
      <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <h5><%= link_to result['name'], result['url'], target: "_blank" %></h5>
        <%= image_tag result['image_url'] %>
        <div class="caption">
        <p>Price: <%= result['price']%></p>
        <%= form_tag items_path target: "_blank" do %>
        <%= hidden_field_tag 'item[name]', result["name"] %>
        <%= hidden_field_tag 'item[url]', result["url"] %>
        <%= hidden_field_tag 'item[image_url]', result["image_url"] %>
        <%= hidden_field_tag 'item[source_id]', result["source_id"] %>
        <%= hidden_field_tag 'item[price]', result["price"] %>
        <%= hidden_field_tag 'item[source_type]', @search.source_type %>
        <p><%= submit_tag 'Add to Closet', class: 'btn btn-primary' %></p>
        <% end %>
        </div>
    </div>
  </div>
</center>
  <% end %>
</div>
<% end %>

app/views/searches/_amazonform.html.erb
<%= form_tag searches_path, method: "get" do %>
  <%= text_field_tag :keyword, 'keyword', class: "form-control", id: "inputDefault", style: "width: 250px;"  %><br>
  <%= hidden_field_tag 'item[source_type]', 'Amazon' %>
  <%= submit_tag 'Search Amazon', class: 'btn btn-default'%>
<% end %>

app/views/searches/_hidefy.html.erb
<%= form_tag searches_path, method: "get" do %>
  <%= text_field_tag :keyword, 'Hidefy', class: "form-control", id: "inputDefault", style: "width: 250px;" %>
  <%= hidden_field_tag 'item[source_type]', 'Hidefy', class: "form-control", id: "inputDefault", style: "width: 250px;" %><br>
  <%= submit_tag 'Search Hidefy', class: 'btn btn-default'%>
<% end %>

app/views/searches/_hidefyform.html.erb
<%= form_tag searches_path, method: "get" do %>
  <%= text_field_tag :keyword, 'Hidefy', class: "form-control", id: "inputDefault", style: "width: 250px;" %>
  <%= hidden_field_tag 'item[source_type]', 'Hidefy', class: "form-control", id: "inputDefault", style: "width: 250px;" %><br>
  <%= submit_tag 'Search Hidefy', class: 'btn btn-default'%>
<% end %>

app/views/searches/index.html.erb
<%= render partial: 'searches/amazon.html.erb' %>

app/views/searches/new.html.erb
<h2> New Search</h2>

<div class="col-sm-3">
  <strong>Find Items on Amazon:</strong>
  <%= render partial: 'searches/amazonform.html.erb' %><br>

  <strong>Find Items on Hidefy:</strong><br>
  <%= render partial: 'searches/hidefyform.html.erb' %>
</div>