config/routes.rb
Rails.application.routes.draw do
  resources :activities
  get 'users/show'

  devise_for :users, controllers: { sessions: "users/sessions" }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :users, only: [:show, :edit, :update] do
    resources :closets
    resources :boards
    member do
      get :following, :followers
    end
  end

  namespace :api, :defaults => { :format => 'json' } do
    resources :users, except: [:new, :edit]
    resources :closets, except: [:new, :edit]
    resources :items, except: [:new, :edit]
  end

  resources :items do
    member do
      put "like", to: "items#upvote"
    end
  end

  get '/prices-over-time', to: 'items#prices_over_time'

  resources :closet_items, only: [:create, :new, :destroy]

  resources :relationships, only: [:create, :destroy]

  devise_scope :user do
    authenticated :user do
        root 'boards#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  get '/hidefy', to: 'searches#hidefy'
  resources :searches

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  name        :string
#  url         :string
#  source_id   :string
#  source_type :string
#  image_url   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Item < ActiveRecord::Base
  has_many :closet_items
  has_many :closets, through: :closet_items, :counter_cache => true
  has_many :prices

  validates :source_id, presence: true, uniqueness: true
  validates :source_type, presence: true
  acts_as_votable

  def exists?
    Item.exists?(source_id: self.source_id)
  end

  def get_hidefy_price(end_path)
    hidefy_item_data = Adapters::HidefyConnection.new.query(end_path)
    current_price = hidefy_item_data["price"]
  end

  def hidefy_create(item_id)
    current_price = get_hidefy_price("items/#{item_id}")
    new_price = Price.new(price: current_price)
    self.prices << new_price
  end

  def self.most_popular
    count = []
    Item.all.each_with_index do |item, i|
      count << item.closets.count
    end
    Item.find(count.index(count.max)+1)
  end

  def get_amazon_price(asin)
    Adapters::AmazonPriceClient.new.get_amazon_price(source_id)
  end

  def last_24hr_prices
    prices_instance_array = prices.where(created_at: (Time.now - 24.hours)..Time.now)
    price_array = []
    prices_instance_array.each do |price|
      price_array << price.price.to_i
    end
    price_array
  end

  def stats
    last_24hrs_array = last_24hr_prices
    stats = DescriptiveStatistics::Stats.new(last_24hrs_array)
    # returns stats instance
  end

  def price_dif
    last_price = self.prices[-1]
    second_last_price = self.prices[-2]
    price_change = last_price.price.to_i - second_last_price.price.to_i
  end

  def prices_over_time
    prices_by_date_created = self.prices.pluck(:created_at, :price).map do |item_price|
      created_time = item_price[0]
      created_time = created_time.strftime('%H:%M')
      [created_time, item_price[1].to_i]
    end
    prices_by_date_created.slice!(0)
    prices_by_date_created
  end

end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController
  def index
    @items = Item.all
    render json: @items
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.exists?
      @item = Item.find_by(source_id: @item.source_id)
    end
    price = params[:item][:price]
    price.slice!(0)
    @item.prices << Price.new(price: price)
    @item.save
    redirect_to new_closet_item_path(:item_id => @item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def upvote
    @item = Item.find(params[:id])
    @item.upvote_by current_user
    redirect_to :back
  end

  def prices_over_time
    item = Item.find(params[:id])
    prices_over_time_array = item.prices_over_time
    render :json => {prices_over_time: prices_over_time_array}
  end

  private

  def item_params
    params.require(:item).permit(:source_id, :name, :url, :image_url, :source_type)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for :item, url: {action: 'create'} do |f|%>
  <div class="field">
    <%= label_tag :closets %><br>
    <% current_user.closets.each do |closet| %>
      <%= check_box_tag 'closet_ids[]', closet.id -%>
      <%= closet.name -%><br>
    <% end %>
  </div><br>
  <div class="actions">
    <%= f.submit class: 'btn btn-default'%>
  </div>
<% end %>

app/views/items/index.html.erb
<h2>All Items</h2>
<% @items.each do |item| %>
  <%= image_tag item.image_url %>
  <%= link_to item.name, item_path(item) %><br>
<% end %>

app/views/items/new.html.erb
<div class="col-md-3">
  <h2>New Item</h2><br>
  <%= render 'form' %><br>

  <strong>Find Items on Amazon:</strong>
  <%= render partial: 'searches/form.html.erb' %>
</div>

app/views/items/show.html.erb
<div class="col-sm-3">
  <h2><%= @item.name %></h2><br>

<%= image_tag @item.image_url %><br>
<strong>Price: </strong><%= @item.prices.last.price %><br>
<strong>Source ID:</strong> <%= @item.source_id %><br>
<%= link_to 'Buy on Amazon', @item.url, target: "_blank", class: "btn btn-success" %><br><br>

  <br><br>
  <h3>Closets:</h3>
  <% @item.closets.each do |closet| %>
    <%= link_to closet.name, user_closet_path(current_user, closet) %><br>
  <% end %>
<br><br>
  <%= link_to 'Add to Closet', new_closet_item_path(:item_id => @item), target: "_blank", class: "btn btn-success" %>
</div>


<div class="col-sm-9">
  <h2>Price</h2>
    <div id = "price-chart">

    </div>
  <!-- graph will go here -->
  
</div>